# -*- coding: utf-8 -*-
"""Base Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109RXBUoMDLe-P-F-HtdeNyRUM7nj4i_P
"""

!pip install xgboost

import pandas as pd
import numpy as np
from xgboost import XGBClassifier, XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_error
from datetime import datetime
import joblib

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Institution_1000_Assets_Invoice_Calibrated.csv")
df.head()

#featyre engineering
current_year = datetime.now().year

df["Asset Age"] = current_year - df["Purchase Year"]

df["Usage Frequency"] = df["Usage Frequency"].map({
    "Low":1,
    "Medium":2,
    "High":3
})

df["Asset Status"] = df["Asset Status"].astype(str).str.strip().str.upper()

df["Asset Status"] = np.where(df["Asset Status"] == "Y", 1, 0)

df["Maintenance Ratio"] = df["Total Maintenance Cost"] / df["Purchase Cost"]

df["Remaining Life"] = df["Useful Life (Years)"] - df["Asset Age"]

df["Annual Depreciation"] = (df["Purchase Cost"] - df["Scrap Value"]) / df["Useful Life (Years)"]

df["Current Book Value"] = df["Purchase Cost"] - (df["Annual Depreciation"] * df["Asset Age"])

df["Asset Status"].isna().sum()

df[df["Asset Status"].isna()]

# model failure
X = df[[
    "Asset Age",
    "Purchase Cost",
    "Usage Frequency",
    "Breakdown Frequency",
    "Maintenance Ratio"
]]

y = df["Asset Status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

model_failure = XGBClassifier(
    n_estimators=400,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model_failure.fit(X_train, y_train)

pred = model_failure.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Failure Prediction Confusion Matrix")
plt.show()

importances = model_failure.feature_importances_

plt.figure(figsize=(8,5))
plt.barh(X.columns, importances)
plt.title("Feature Importance")
plt.show()

plt.figure(figsize=(6,5))
plt.scatter(df["Asset Age"], df["Breakdown Frequency"])
plt.xlabel("Asset Age")
plt.ylabel("Breakdown Frequency")
plt.title("Asset Age vs Breakdown")
plt.show()

plt.figure(figsize=(6,5))
plt.scatter(df["Asset Age"], df["Current Book Value"])
plt.xlabel("Asset Age")
plt.ylabel("Current Book Value")
plt.title("Depreciation Pattern")
plt.show()

#remaining life
X2 = df[["Asset Age","Breakdown Frequency","Total Maintenance Cost"]]
y2 = df["Remaining Life"]

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X2, y2,
    test_size=0.3,
    random_state=42
)

model_rul = XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)

model_rul.fit(X_train2, y_train2)

pred2 = model_rul.predict(X_test2)

print("Remaining Life MAE:", mean_absolute_error(y_test2, pred2))

# eemaining useful life
X_rul = df[[
    "Asset Age",
    "Breakdown Frequency",
    "Maintenance Ratio"
]]

y_rul = df["Remaining Life"]

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_rul, y_rul,
    test_size=0.3,
    random_state=42
)

model_rul = XGBRegressor(
    n_estimators=400,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)

model_rul.fit(X_train2, y_train2)

pred_rul = model_rul.predict(X_test2)

print("RUL MAE:", mean_absolute_error(y_test2, pred_rul))

from sklearn.metrics import roc_curve, auc

probs = model_failure.predict_proba(X_test)[:,1]
fpr, tpr, _ = roc_curve(y_test, probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.show()

print("AUC:", roc_auc)

# depriciation
X_dep = df[[
    "Asset Age",
    "Purchase Cost",
    "Breakdown Frequency"
]]

y_dep = df["Current Book Value"]

X_train3, X_test3, y_train3, y_test3 = train_test_split(
    X_dep, y_dep,
    test_size=0.3,
    random_state=42
)

model_dep = XGBRegressor(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)

model_dep.fit(X_train3, y_train3)

pred_dep = model_dep.predict(X_test3)

print("Depreciation MAE:", mean_absolute_error(y_test3, pred_dep))

#maintainence forecast
X_cost = df[[
    "Asset Age",
    "Usage Frequency",
    "Breakdown Frequency"
]]

y_cost = df["Total Maintenance Cost"]

X_train4, X_test4, y_train4, y_test4 = train_test_split(
    X_cost, y_cost,
    test_size=0.3,
    random_state=42
)

model_cost = XGBRegressor(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)

model_cost.fit(X_train4, y_train4)

pred_cost = model_cost.predict(X_test4)

print("Maintenance Cost MAE:", mean_absolute_error(y_test4, pred_cost))

def repair_replace_decision(row):
    if (
        row["Total Maintenance Cost"] > 0.6 * row["Purchase Cost"]
        or row["Breakdown Frequency"] > 5
        or row["Remaining Life"] < 1
    ):
        return "Replace"
    else:
        return "Repair"

df["Recommendation"] = df.apply(repair_replace_decision, axis=1)

joblib.dump(model_failure, "failure_model.pkl")
joblib.dump(model_rul, "rul_model.pkl")
joblib.dump(model_dep, "depreciation_model.pkl")
joblib.dump(model_cost, "cost_model.pkl")

from google.colab import files

files.download("failure_model.pkl")
files.download("rul_model.pkl")
files.download("depreciation_model.pkl")
files.download("cost_model.pkl")